linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - sqlclosecheck

linters-settings:
  gosec:
    excludes:
      - G204  # subprocess launched with variable - we validate channel names

issues:
  exclude-use-default: false
